### ISSUE TITLE
Text is not rendered when new line is inserted by autocompletion

### ISSUE THREAD

**Issue by LinqLover** [MrModder/Autocompletion#11]
### Steps to Reproduce
Resize a workspace window and type the following, for example:
![image](https://user-images.githubusercontent.com/38782922/51927966-1b179200-23f5-11e9-9c8c-99576aaa804b.png)
Then press tab. I see the following now:
![image](https://user-images.githubusercontent.com/38782922/51927982-25d22700-23f5-11e9-8b59-96f0a1fe9070.png)

### Expected Behavior
The text should be normally displayed as if you had typed the word manually:
![image](https://user-images.githubusercontent.com/38782922/51928114-6d58b300-23f5-11e9-8cde-9814250ba409.png)

Kind regards!

**Comment by LeonMatthes** [comment]
Hi, thank you for using the Autocompletion, and thanks for the bug report.
This should now be fixed in the latest commit.
You have to install the new changes with this code:
``` smalltalk
Metacello new
	baseline: 'Autocompletion';
	get; "Notice the get here!"
	load.
```
Please confirm, that the bug is gone in your image too, so I can close the issue.

**Comment by LinqLover** [comment]
I am sorry to say that whenever I execute this command, I get an error:

Could not resolve: BaselineOfAutocompletion [BaselineOfAutocompletion] in ...
________________________________
Von: Leon Matthes <notifications@github.com>
Gesendet: Mittwoch, 30. Januar 2019 14:27 Uhr
An: MrModder/Autocompletion
Cc: TChristoph; Author
Betreff: Re: [MrModder/Autocompletion] Text is not rendered when new line is inserted by autocompletion (#11)


Hi, thank you for using the Autocompletion, and thanks for the bug report.
This should now be fixed in the latest commit.
You have to install the new changes with this code:

Metacello new
        baseline: 'Autocompletion';
        get; "Notice the get here!"
        load.

Please confirm, that the bug is gone in your image too, so I can close the issue.

**Comment by LeonMatthes** [comment]
Oh, sorry, I forgot to add the repository url to the Metacello command.
You should run either:
``` smalltalk
Metacello new
	repository: 'github://MrModder/Autocompletion:master/packages';
	baseline: 'Autocompletion';
	get;
	load.
```

Or: 
``` smalltalk
Metacello image "image will use the repository you used last time for this package"
	baseline: 'Autocompletion';
	get;
	load.
```

**Comment by LinqLover** [comment]
Ah, now it works. I am pleased I cannot reproduce the issue any longer, thank you!
________________________________
Von: Leon Matthes <notifications@github.com>
Gesendet: Freitag, 1. Februar 2019 09:15 Uhr
An: MrModder/Autocompletion
Cc: TChristoph; Author
Betreff: Re: [MrModder/Autocompletion] Text is not rendered when new line is inserted by autocompletion (#11)


Oh, sorry, I forgot to add the repository url to the Metacello command.
You should run either:

Metacello new
        repository: 'github://MrModder/Autocompletion:master/packages';
        baseline: 'Autocompletion';
        get;
        load.

Or:

Metacello image "image will use the repository you used last time for this package"
        baseline: 'Autocompletion';
        get;
        load.

**Comment by LeonMatthes** [comment]
Ok, great, thank you for helping me improve the Autocompletion
