### ISSUE TITLE
Use debugger type info

### ISSUE THREAD

**Issue by tom95** [MrModder/Autocompletion#17]
Not sure if this already in: for the case where I'm editing code in the debugger, there is already a lot of type information available. Using this could provide very accurate and helpful completions.

**Comment by LeonMatthes** [comment]
No, thats currently not supported.
But a good idea, I will look into it 👍

**Comment by LinqLover** [comment]
Hey @tom95 did c46ac70 support all kinds of type information you were having in mind? :)

![image](https://github.com/LeonMatthes/Autocompletion/assets/38782922/9d0ec0c5-e7cd-4667-bbe1-6c6b2c16840a)

**Comment by tom95** [comment]
I think so, yes. Thank you!
