### ISSUE TITLE
Suggest second part of method name after autocompleting

### ISSUE THREAD

**Issue by bdaase** [MrModder/Autocompletion#2]
Imagine I want to type the following code:
`1 to: 5 do: [...]`.  

If I type `1 to` and use the autocompletion I get `1 to:`. If I now continue typing the `d` I get several suggestions but not the `do:` which would be the second part of the `to: do:` message. But that would be a cool feature.

**Comment by LeonMatthes** [comment]
This is not really doable as the Autocompletion will try to find suggestions for the 5.
This is the correct behaviour in this case as we never know whether we want to find the completion for the current object or a larger call.
If you choose the correct completion in the first place you also get additional perks like multi-argument tab-switching (#1). So you should try to get used to selecting the correct completion. I know this is a bit of a learning curve, but worth it at the end.
