### ISSUE TITLE
Autocompletion does not work in Debugger (#wantsToCloseAutocompletion)

### ISSUE THREAD

**Issue by LinqLover** [MrModder/Autocompletion#21]
After loading 8cc9dfc, Autocompletion will no longer be shown in Debugger (but flashes for a very short time). This can be solved by overriding `#wantsToCloseAutocompletion` in Inspector as follows:
```Smalltalk
^ self containingMorphicModels isEmpty
```
But when I overrided this selector locally, I wondered why not to change the implementation in StringHolder itself, so that all containing morphs are considered in every case? Is there any case where this would be an unwanted behavior?

**Comment by LeonMatthes** [comment]
I was unable to reproduce this issue locally with the current version of Autocompletion, have you tried updating it?

Furthermore, in my image, the message `containgMorphicModels` does not seem to exist.
Also, what does the implementation in Inspector have to do with the Debugger?

**Comment by LinqLover** [comment]
I am sorry for the inaccurate bug report: I meant typing into the _inspector panes_ of the debugger ("Select receiver's/context's field"). The reason is that their text morphs are assigned to (sub)instances of Inspector, for which the containingWindow is nil. For me, the issue exists still in f79b826. Can you reproduce this?

`Model>>containingMorphicModels` is an extension developed in context of SqueakSheet:

```Smalltalk
containingMorphicModels
	"Answer the MorphicModels that hold the receiver."

	^ self dependents select: #isMorphicModel
```

While the Debugger's bottom text fields are not a containingWindow to the receiverInspector of the Debugger, they are contained in the inspector's containingMorphicModels which we could search to find out whether the autocompletion menu is still relevant (when the window closes, all dependents should be broken from the model in SystemWindow>>delete).

Indeed, this proposal would not work for the Debugger's inspector panes at the moment. I think this is a rather a bug in the framework, as neither on #release nor on #windowIsClosing, the debuggers calls #release on its receiverInspector. Do you think this would be worth a commit to the Squeak Inbox?

Have a nice weekend!
