### ISSUE TITLE
Wrong receiver for Inspectors

### ISSUE THREAD

**Issue by LinqLover** [MrModder/Autocompletion#26]
Scenario:
- Preference "include all selectors" is disabled
- Open an inspector, e. g. on a Morph
- Start typing into the right pane
- If you select no instvar, the Autocompletion will suggest e. g. `bounds` correctly
- But if you select any instvar (for example bounds), `bounds` will not be suggested -- but instead, `origin` and `corner`
- But you can only evaluate `bounds`, not `origin`

Reason:
- ECController asks the model for #selectedClassOrMetaClass
- Default implementation of this is #selectedClass
- Inspector>>#selectedClass returns the class of the current selected instvar
- In this case, the selection does not affect the code that can be evaluated

Questions and solution approaches:
- I am wondering whether the only purpose of #selectedClassOrMetaClass is to be used by Autocompletion? At least, it is in the Autocompletion category, but the on the other hand it has many other senders in Browser, Debugger, pp. In general, what differentiates #selectedClassOrMetaClass from #selectedClass? Are there historical reasons?
- For what purpose does Inspector>>#selectedClass return the class of the selected instvar instead of `object class`?
- If we could freely dispose of #selectedClassOrMetaClass, the solution would be to override it in Inspector to return `object class`.
- Otherwise, we would probably need another selector?

**Comment by LeonMatthes** [comment]
This is a known bug, thanks for filing the issue.

I'm actually not sure myself where selectedClassOrMetaClass comes from orginally.
But overriding it in the Inspector seems to be the best option to solving this issue.

**Comment by LinqLover** [comment]
Do you think this method should be overridden in the #'*Autocompletion' category or directly into the Inbox?

**Comment by LeonMatthes** [comment]
Fixed in #29
