### ISSUE TITLE
AlphaBlendingCanvas extension

### ISSUE THREAD

**Issue by LinqLover** [MrModder/Autocompletion#36]
Referring to the extension method `#image:at:sourceRect:rule:` in `AlphaBlendingCanvas` (which, btw, is missing the `-override` suffix in the extension category name), see https://github.com/MrModder/Autocompletion/commit/ced56775bebb040ab3e413411e312d0d6978df5f#diff-f8e09250df8680dcca55dfd0177755ff: 
Could you please provide a short description of this fix? I'd love to see this in Trunk because it shadows the original method version and thus keeps a "removed method" in my Monticello working copy.

**Comment by LeonMatthes** [comment]
I honestly don't remember why this fix is done the way it is :thinking: .

Pretty sure it fixes that text drawn by Autocompletion wasn't fading correctly with the ECMenuMorph though.

Where did you find the convention on using an `-override`-Suffix?

**Comment by LinqLover** [comment]
Hm, I'd like to get this into the trunk, but I do not even know enough about drawing to describe the sense of the change ...

Probably related resource (because it also concerns the function of the different `Form` rules): [[squeak-dev] ColorForm with transparency not working properly
](http://forum.world.st/ColorForm-with-transparency-not-working-properly-td5122224.html)

> Where did you find the convention on using an -override-Suffix?

See `PackageInfo >> #isOverrideCategory:`, `MCMethodDefinition >> #isOverrideMethod`, and this thread on squeak-dev: [Re: Possible buggy senders of Class >> #category?](http://forum.world.st/Possible-buggy-senders-of-Class-category-tp5108121p5108282.html) (where it also turns out that this is not documented properly indeed). Citing Vanessa Freudenberg:

> > (It would be great if we had some "recover stashed code" logic someday: If a package is uninstalled, don't remove all extension methods, but check for previous versions that are not in the package which is currently to be uninstalled and, if found, revert to the latest original version.)
> 
> That's exactly what's supposed to happen, if you properly named your category "*xyz-override". By marking a method as override, it belongs to both the original package and the overriding package.

**Comment by LinqLover** [comment]
When I revert the method to the original trunk version, the fading animation still works as expected. Should we just remove the extension method from this repository?

**Comment by LeonMatthes** [comment]
Hm, this might also have had something to do with drawing images into the Autocompletion entries, which we were doing for BlocksToTheRescue with a custom ECEntryHook.
That's probably also why @ShirleyNekoDev is mentioned in the commit.

But again, I'm still very uncertain why that code is the way it is...
Unless it's actively conflicting with a new version in Trunk, I'd just like to keep it as-is
It's now correctly recategorized as `-override`.
