### ISSUE TITLE
Add Squeak in the project description for GitHub search

### ISSUE THREAD

**Issue by j4yk** [MrModder/Autocompletion#48]
I tried to search for this repository today using the GitHub search, but could not find it with the terms "autocompletion squeak". Could you please add Squeak somehow in the project description, so that this repository will show up with these search terms?

**Comment by LinqLover** [comment]
Maybe the repo also needs more inbound links. Should we create an Swiki page for it?

**Comment by j4yk** [comment]
You could add it here: http://wiki.squeak.org/squeak/3446

**Comment by LinqLover** [comment]
@LeonMatthes If you agree with this, I can link this project on Swiki.

**Comment by LeonMatthes** [comment]
@LinqLover Sure, go ahead.
Added Squeak to the GH Repository description + a few keywords
