### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by BraunTom** [MrModder/Autocompletion#9]
It would be nice to have the ability to create custom entries in the autocompletion that gets suggested and extended if you choose them.
example: in webstorm I have a clg entry in my autocompletion that expands to console.log
Maybe it would be possible to create general entries (e.g. tsl => Transcript showln: ) and for classes and their subclasses (e.g. itf => ifTrue: ifFalse: for the Boolean class)

**Comment by LeonMatthes** [comment]
Now moved to https://github.com/BraunTom/Snippets
